#!/bin/bash

#
# lxc: linux Container library

# Copyright (c) 2013, Masato Taruishi <taru0216@gmail.com>

# Authors:
# Masato Taruishi <taru0216@gmail.com>


ARCHIVEDIR=/var/lib/ips-cell/sandbox/archive


install_archive()
{
    path=$1
    name=$2
    archive=$3

    echo -n "Installing '$name' with $archive... "
    /bin/cp $path/config $path/config.bak
    install -d $rootfs && tar --strip-components=1 \
        -jxf $archive -C $path --checkpoint=100
    /bin/mv $path/config.bak $path/config
    echo "done"

    return 0
}

configure_archive()
{
    rootfs=$1
    return 0
}

copy_configuration()
{
    path=$1
    rootfs=$2
    name=$3

    ttydir=""
    if [ -f $rootfs/etc/init/container-detect.conf ]; then
        ttydir=" lxc"
    fi

    # if there is exactly one veth network entry, make sure it has an
    # associated hwaddr.
    nics=`grep -e '^lxc\.network\.type[ \t]*=[ \t]*veth' $path/config | wc -l`
    if [ $nics -eq 1 ]; then
        grep -q "^lxc.network.hwaddr" $path/config || cat <<EOF >> $path/config
lxc.network.hwaddr = 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
EOF
    fi

    grep -q "^lxc.rootfs" $path/config 2>/dev/null || echo "lxc.rootfs = $rootfs" >> $path/config
    cat <<EOF >> $path/config
lxc.utsname = $name

lxc.devttydir =$ttydir
lxc.tty = 4
lxc.pts = 1024
lxc.mount  = $path/fstab
lxc.arch = amd64
lxc.cap.drop = sys_module mac_admin mac_override
lxc.pivotdir = lxc_putold

# uncomment the next line to run the container unconfined:
#lxc.aa_profile = unconfined

EOF
    if [ -f $path/devices ]; then
        cat $path/devices >> $path/config
    else
        cat <<EOF >> $path/config
lxc.cgroup.devices.deny = a
# Allow any mknod (but not using the node)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
#lxc.cgroup.devices.allow = c 4:0 rwm
#lxc.cgroup.devices.allow = c 4:1 rwm
# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
# rtc
lxc.cgroup.devices.allow = c 254:0 rwm
#fuse
lxc.cgroup.devices.allow = c 10:229 rwm
#tun
lxc.cgroup.devices.allow = c 10:200 rwm
#full
lxc.cgroup.devices.allow = c 1:7 rwm
#hpet
lxc.cgroup.devices.allow = c 10:228 rwm
#kvm
lxc.cgroup.devices.allow = c 10:232 rwm
EOF
    fi
    if [ $? -ne 0 ]; then
        echo "Failed to add configuration"
        return 1
    fi

    return 0
}

usage()
{
    cat <<EOF
$1 -h|--help -p|--path=<path> -a|--archive=<archive>
EOF
    return 0
}

options=$(getopt -o ha:p:n: -l help,archive:,path:,name: -- "$@")
if [ $? -ne 0 ]; then
        usage $(basename $0)
    exit 1
fi
eval set -- "$options"

while true
do
    case "$1" in
        -h|--help)      usage $0 && exit 0;;
        -p|--path)      path=$2; shift 2;;
    	-n|--name)      name=$2; shift 2;;
    	-a|--archive)   archive=$2; shift 2;;
        --)             shift 1; break ;;
        *)              break ;;
    esac
done

if [ -z "$archive" ]; then
    echo "'archive' parameter is required"
    exit 1
fi

if ! [ -f $archive ]; then
    echo "File not found: $archive"
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script should be run as 'root'"
    exit 1
fi

if [ -z "$path" ]; then
    echo "'path' parameter is required"
    exit 1
fi

# detect rootfs
config="$path/config"
if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
    rootfs=`grep 'lxc.rootfs =' $config | awk -F= '{ print $2 }'`
else
    rootfs=$path/rootfs
fi

install_archive $path $name "$archive"
if [ $? -ne 0 ]; then
    echo "failed to install $name's rootfs"
    exit 1
fi

configure_archive $rootfs
if [ $? -ne 0 ]; then
    echo "failed to configure archive template"
    exit 1
fi

copy_configuration $path $rootfs $name
if [ $? -ne 0 ]; then
    echo "failed to write configuration file"
    exit 1
fi
