#!/usr/bin/env python

__author__ = 'Masato Taruishi'
__copyright__ = 'Copyright (c) 2013, Masato Taruishi <taru0216@gmail.com>'


import google.protobuf.text_format
import ips.handlers
import ips.proto
import sys


USAGE = """
Usage: ips-rpc-client \\
    <host>:<port> <service> <method> <request protobuf>
e.g.

$ ips-rpc-list localhost:6195 ips_proto_sandbox.SandboxService getSandboxes ''
"""


def main():
  if len(sys.argv) != 5:
    print USAGE
    sys.exit(1)

  host = sys.argv[1]
  service_name = sys.argv[2]
  method_name = sys.argv[3]
  text_proto = sys.argv[4]
  
  method, argument = ips.handlers.FormzRpcClient.GetMethodAndRequest(
      service_name, method_name)
  google.protobuf.text_format.Merge(text_proto, argument)

  rpc_client = ips.handlers.FormzRpcClient(host)

  print rpc_client.Call(method, argument)


if __name__ == '__main__':
  main()
